// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp1rUzOZj-RtS9u4Tgp-whapKbUKRFUDw',
    appId: '1:515207484899:web:a9c9d081447e16573d7cd6',
    messagingSenderId: '515207484899',
    projectId: 'sampah-mobile',
    authDomain: 'sampah-mobile.firebaseapp.com',
    storageBucket: 'sampah-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7UNFbkLLiKF5wODZueBtMNwkOtXdhznI',
    appId: '1:515207484899:android:7ae94868cfc276733d7cd6',
    messagingSenderId: '515207484899',
    projectId: 'sampah-mobile',
    storageBucket: 'sampah-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUJieouhv0IZkrgrw0wWw4T54Q9LT02Lc',
    appId: '1:515207484899:ios:621ba689f90bbade3d7cd6',
    messagingSenderId: '515207484899',
    projectId: 'sampah-mobile',
    storageBucket: 'sampah-mobile.firebasestorage.app',
    iosBundleId: 'com.example.sampahOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUJieouhv0IZkrgrw0wWw4T54Q9LT02Lc',
    appId: '1:515207484899:ios:621ba689f90bbade3d7cd6',
    messagingSenderId: '515207484899',
    projectId: 'sampah-mobile',
    storageBucket: 'sampah-mobile.firebasestorage.app',
    iosBundleId: 'com.example.sampahOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp1rUzOZj-RtS9u4Tgp-whapKbUKRFUDw',
    appId: '1:515207484899:web:b8850c5d9d6de03e3d7cd6',
    messagingSenderId: '515207484899',
    projectId: 'sampah-mobile',
    authDomain: 'sampah-mobile.firebaseapp.com',
    storageBucket: 'sampah-mobile.firebasestorage.app',
  );
}
